font_family Consolas
bold_font auto
italic_font auto
bold_italic_font auto

# Material Theme Darker matching VS Code
foreground #c6c6c6
background #191919
cursor     #c3e88d
cursor_text_color #131313

# Selection
selection_foreground #ffffff
selection_background #242424

# Black
color0 #545454
color8 #737373

# Red
color1 #f07178
color9 #f07178

# Green
color2  #c3e88d
color10 #c3e88d

# Yellow
color3  #ffcb6b
color11 #ffcb6b

# Blue
color4  #82aaff
color12 #3b8eea

# Magenta
color5  #c792ea
color13 #c792ea

# Cyan
color6  #abdcfd
color14 #abdcfd

# White
color7  #c6c6c6
color15 #e5e5e5

# Transparency
background_opacity 0.8
window_padding_width 8
shell zsh
